apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-serivce
  namespace: product-service
  labels: 
    app: product-service
spec: 
  replicas: 2
  selector:
    matchLabels :
      app : product-service
  template: 
    metadata:
      labels: 
        app: product-service
    spec:
      containers : 
      - name : product-service
        image : lmalkam/product-service:latest
        ports:
          - containerPort: 5001
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_URI
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: product-service-config
                key: PORT
