apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-serivce
  namespace: product-service
  labels: 
    app: product-service
spec: 
  replicas: 2
  selector:
    matchLabels :
      app : product-service
  template: 
    metadata:
      labels: 
        app: product-service
  
    spec:
      containers : 
      - name : product-service
        image : lmalkam/product-service:latest
        port:
          - containerPorts : 5001